### ISSUE TITLE
Not working G Trends

### ISSUE THREAD

**Issue by milandzuris** [b0mbays/google_trends#1]
Logger: homeassistant.components.sensor
Source: custom_components/google_trends/google_trends.py:6
Integration: Sensor (documentation, issues)
First occurred: 01:41:50 (1 occurrences)
Last logged: 01:41:50

Error while setting up google_trends platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/google_trends/sensor.py", line 29, in async_setup_entry
    trends = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_trends/google_trends.py", line 6, in get_top_trends
    trending_searches_df = pytrends.trending_searches(pn=country_code)
  File "/usr/local/lib/python3.10/site-packages/pytrends/request.py", line 474, in trending_searches
    req_json = self._get_data(
KeyError: 'slovakia'

**Comment by b0mbays** [comment]
Hey @milandzuris , I assume you fixed this?

**Comment by milandzuris** [comment]
> Hey @milandzuris , I assume you fixed this?

My country is not supported

**Comment by b0mbays** [comment]
Unfortunately I don't see Slovakia on the list that Google supports 😞 You can find them here:

https://trends.google.com/trends/trendingsearches/daily?geo=GB&hl=en-GB

Change the dropdown towards the top. Unfortunately there is no way for me to "add a country" as this is driven by Google. Sorry!

**Comment by b0mbays** [comment]
Is there anymore you need help with @milandzuris ? I'll close the issue if this is resolved.
